//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniproject_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.cancellations = new HashSet<cancellation>();
        }
    
        public int booking_id { get; set; }
        public Nullable<int> train_No { get; set; }
        public string @class { get; set; }
        public System.DateTime data_of_booking { get; set; }
        public System.DateTime data_of_travelling { get; set; }
        public Nullable<int> total_seats { get; set; }
        public Nullable<double> total_amount { get; set; }
        public string status { get; set; }
    
        public virtual train train { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cancellation> cancellations { get; set; }
    }
}
