//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniproject_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssignmentDbEntities : DbContext
    {
        public AssignmentDbEntities()
            : base("name=AssignmentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_details> admin_details { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<cancellation> cancellations { get; set; }
        public virtual DbSet<train> trains { get; set; }
    
        public virtual int InsertBookingAndUpdateTrainWithDates(Nullable<int> booking_id, Nullable<int> train_no, string @class, Nullable<System.DateTime> data_of_booking, Nullable<System.DateTime> date_of_travelling, Nullable<int> total_seats)
        {
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("booking_id", booking_id) :
                new ObjectParameter("booking_id", typeof(int));
    
            var train_noParameter = train_no.HasValue ?
                new ObjectParameter("train_no", train_no) :
                new ObjectParameter("train_no", typeof(int));
    
            var classParameter = @class != null ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(string));
    
            var data_of_bookingParameter = data_of_booking.HasValue ?
                new ObjectParameter("data_of_booking", data_of_booking) :
                new ObjectParameter("data_of_booking", typeof(System.DateTime));
    
            var date_of_travellingParameter = date_of_travelling.HasValue ?
                new ObjectParameter("date_of_travelling", date_of_travelling) :
                new ObjectParameter("date_of_travelling", typeof(System.DateTime));
    
            var total_seatsParameter = total_seats.HasValue ?
                new ObjectParameter("total_seats", total_seats) :
                new ObjectParameter("total_seats", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertBookingAndUpdateTrainWithDates", booking_idParameter, train_noParameter, classParameter, data_of_bookingParameter, date_of_travellingParameter, total_seatsParameter);
        }
    
        public virtual int InsertCancellationAndUpdateTrainWithRefund(Nullable<int> cancel_id, Nullable<int> booking_id, string @class, Nullable<System.DateTime> cancel_date, Nullable<int> no_of_seats, string remarks)
        {
            var cancel_idParameter = cancel_id.HasValue ?
                new ObjectParameter("cancel_id", cancel_id) :
                new ObjectParameter("cancel_id", typeof(int));
    
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("booking_id", booking_id) :
                new ObjectParameter("booking_id", typeof(int));
    
            var classParameter = @class != null ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(string));
    
            var cancel_dateParameter = cancel_date.HasValue ?
                new ObjectParameter("cancel_date", cancel_date) :
                new ObjectParameter("cancel_date", typeof(System.DateTime));
    
            var no_of_seatsParameter = no_of_seats.HasValue ?
                new ObjectParameter("no_of_seats", no_of_seats) :
                new ObjectParameter("no_of_seats", typeof(int));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCancellationAndUpdateTrainWithRefund", cancel_idParameter, booking_idParameter, classParameter, cancel_dateParameter, no_of_seatsParameter, remarksParameter);
        }
    }
}
